version: "3"

services:
  app:
    networks:
      - global
    build:
      context: .
      target: install-deps
    ports:
      - 5000:5000
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - FLASK_DEBUG=1
    volumes:
      - .:/app:z
    depends_on:
      - "db"
  db:
    image: postgres
    restart: always
    networks:
      - global
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5435:5432
    volumes:
      - /var/lib/postgresql/data

networks:
  global:
