"""add_article_upload

Revision ID: 0530dccdab64
Revises: b0dd1737b940
Create Date: 2022-02-09 11:24:35.692277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0530dccdab64'
down_revision = 'b0dd1737b940'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('upload_hash', sa.String(), nullable=True))
    op.create_foreign_key(op.f('fk_articles_upload_hash_uploads'), 'articles', 'uploads', ['upload_hash'], ['hash'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_articles_upload_hash_uploads'), 'articles', type_='foreignkey')
    op.drop_column('articles', 'upload_hash')
    # ### end Alembic commands ###
