"""add_is_complete_package

Revision ID: 090398e59893
Revises: cd4c0b1ade27
Create Date: 2022-01-27 16:12:53.850850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '090398e59893'
down_revision = 'cd4c0b1ade27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages', sa.Column('is_complete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('packages', 'is_complete')
    # ### end Alembic commands ###
