"""empty message

Revision ID: 09e9a9e4fb28
Revises: e9490e55f2b4
Create Date: 2022-01-03 17:56:56.437247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09e9a9e4fb28'
down_revision = 'e9490e55f2b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('letters', sa.Column('status', sa.Enum('not_moderated', 'approved', 'rejected', name='status', native_enum=False), server_default='not_moderated', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('letters', 'status')
    # ### end Alembic commands ###
