"""Add recipient type

Revision ID: 0b8d6cd7c53c
Revises: 27b5bec2bd8a
Create Date: 2021-12-13 16:23:43.405255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b8d6cd7c53c'
down_revision = '27b5bec2bd8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipient_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipient_types'))
    )
    op.add_column('recipients', sa.Column('type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_recipients_type_id_recipient_types'), 'recipients', 'recipient_types', ['type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_recipients_type_id_recipient_types'), 'recipients', type_='foreignkey')
    op.drop_column('recipients', 'type_id')
    op.drop_table('recipient_types')
    # ### end Alembic commands ###
