"""add_writing_session_language

Revision ID: 1ddb1f134e37
Revises: 323e1afa2336
Create Date: 2022-03-11 12:15:01.120904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ddb1f134e37'
down_revision = '323e1afa2336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('writing_sessions', sa.Column('language_code', sa.String(), nullable=True))
    op.create_foreign_key(op.f('fk_writing_sessions_language_code_languages'), 'writing_sessions', 'languages', ['language_code'], ['code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_writing_sessions_language_code_languages'), 'writing_sessions', type_='foreignkey')
    op.drop_column('writing_sessions', 'language_code')
    # ### end Alembic commands ###
