"""add name recipient

Revision ID: 27b5bec2bd8a
Revises: e529c728ab5c
Create Date: 2021-12-10 16:24:14.946570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27b5bec2bd8a'
down_revision = 'e529c728ab5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipients', sa.Column('name', sa.String(), nullable=True))
    op.add_column('recipients', sa.Column('receives_letters', sa.Boolean(), nullable=True))
    op.drop_column('recipients', 'receive_letters')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipients', sa.Column('receive_letters', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('recipients', 'receives_letters')
    op.drop_column('recipients', 'name')
    # ### end Alembic commands ###
