"""add phone to recipients

Revision ID: 322a17755fba
Revises: a4a8da004370
Create Date: 2022-06-08 18:02:21.116108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '322a17755fba'
down_revision = 'a4a8da004370'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipients', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipients', 'phone')
    # ### end Alembic commands ###
