"""add_admin_editing_perm

Revision ID: 3f868851df3a
Revises: 09e9a9e4fb28
Create Date: 2022-01-11 12:04:44.015240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f868851df3a'
down_revision = '09e9a9e4fb28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('can_edit_recipients', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'can_edit_recipients')
    # ### end Alembic commands ###
