"""Add country names

Revision ID: 418465478ae6
Revises: 322a17755fba
Create Date: 2022-06-08 22:03:27.653570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '418465478ae6'
down_revision = '322a17755fba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('countries', 'name')
    # ### end Alembic commands ###
