"""add_user_pending_recipients

Revision ID: 56604e11d48c
Revises: d323271019bd
Create Date: 2022-03-16 10:17:27.178507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56604e11d48c'
down_revision = 'd323271019bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_pending_recipients',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['recipients.id'], name=op.f('fk_users_pending_recipients_recipient_id_recipients')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_users_pending_recipients_user_id_users'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_pending_recipients')
    # ### end Alembic commands ###
