"""set email and country_code to nullable

Revision ID: 696f758f794e
Revises: 551505051861
Create Date: 2022-05-21 14:03:24.256154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '696f758f794e'
down_revision = '551505051861'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('letters', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('letters', 'country_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('recipients', 'country_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('schools', 'country_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schools', 'country_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('recipients', 'country_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('letters', 'country_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('letters', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
