"""add_moderation_time_letter

Revision ID: 766c68796ed1
Revises: 3f868851df3a
Create Date: 2022-01-12 14:08:54.619926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '766c68796ed1'
down_revision = '3f868851df3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('letters', sa.Column('moderation_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('letters', 'moderation_time')
    # ### end Alembic commands ###
