"""add_package

Revision ID: 7b30d343eb8c
Revises: bebe1f57b08d
Create Date: 2022-01-20 16:59:17.095710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b30d343eb8c'
down_revision = 'bebe1f57b08d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('file', sa.String(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['recipients.id'], name=op.f('fk_packages_recipient_id_recipients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_packages'))
    )
    op.create_table('packages_letters',
    sa.Column('letter_id', sa.Integer(), nullable=True),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['letter_id'], ['letters.id'], name=op.f('fk_packages_letters_letter_id_letters')),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], name=op.f('fk_packages_letters_package_id_packages'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('packages_letters')
    op.drop_table('packages')
    # ### end Alembic commands ###
