"""add letter gender and age

Revision ID: b045b95f427f
Revises: bebe1f57b08d
Create Date: 2022-01-20 17:04:05.486600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b045b95f427f'
down_revision = 'bebe1f57b08d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('letters', sa.Column('is_male', sa.Boolean(), server_default='1', nullable=False))
    op.add_column('letters', sa.Column('is_young', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('letters', 'is_young')
    op.drop_column('letters', 'is_male')
    # ### end Alembic commands ###
