"""add_writing_session_title_and_relationship_with_letter

Revision ID: be5589e42eef
Revises: 0530dccdab64
Create Date: 2022-02-22 15:15:36.585975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be5589e42eef'
down_revision = '0530dccdab64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('letters', sa.Column('writing_session_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_letters_writing_session_id_writing_sessions'), 'letters', 'writing_sessions', ['writing_session_id'], ['id'])
    op.add_column('writing_sessions', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('writing_sessions', 'title')
    op.drop_constraint(op.f('fk_letters_writing_session_id_writing_sessions'), 'letters', type_='foreignkey')
    op.drop_column('letters', 'writing_session_id')
    # ### end Alembic commands ###
