"""add_school_associated_recipient

Revision ID: d323271019bd
Revises: 1ddb1f134e37
Create Date: 2022-03-14 15:55:52.698575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd323271019bd'
down_revision = '1ddb1f134e37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schools', sa.Column('recipient_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_schools_recipient_id_recipients'), 'schools', 'recipients', ['recipient_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_schools_recipient_id_recipients'), 'schools', type_='foreignkey')
    op.drop_column('schools', 'recipient_id')
    # ### end Alembic commands ###
