"""add letter theme

Revision ID: d54cd1104d13
Revises: fe734d68b2fd
Create Date: 2022-01-25 13:09:56.029308

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd54cd1104d13'
down_revision = 'fe734d68b2fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('greetings')
    op.add_column('letters', sa.Column('theme', sa.Enum('travel', 'funny', 'emotional', 'other', name='theme', native_enum=False), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('letters', 'theme')
    op.create_table('greetings',
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.UniqueConstraint('key', name='uq_greetings_key')
    )
    # ### end Alembic commands ###
