"""add hash upload fk

Revision ID: e529c728ab5c
Revises: 904a362f6318
Create Date: 2021-12-10 16:21:29.383325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e529c728ab5c'
down_revision = '904a362f6318'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('letters', sa.Column('upload_hash', sa.String(), nullable=True))
    op.create_foreign_key(op.f('fk_letters_upload_hash_uploads'), 'letters', 'uploads', ['upload_hash'], ['hash'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_letters_upload_hash_uploads'), 'letters', type_='foreignkey')
    op.drop_column('letters', 'upload_hash')
    # ### end Alembic commands ###
