"""Add admin perms

Revision ID: e9490e55f2b4
Revises: 308c14d89f3e
Create Date: 2021-12-31 20:16:49.523767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9490e55f2b4'
down_revision = '308c14d89f3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('can_moderate', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('can_see_stats', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'can_see_stats')
    op.drop_column('users', 'can_moderate')
    # ### end Alembic commands ###
