"""Add initial db models

Revision ID: ed00e9053bc0
Revises: fa0544f4762d
Create Date: 2021-12-08 15:50:22.028001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed00e9053bc0'
down_revision = 'fa0544f4762d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_countries'))
    )
    op.create_table('greetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_greetings'))
    )
    op.create_table('languages',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('accepts_letters', sa.Boolean(), nullable=True),
    sa.Column('has_translations', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_languages'))
    )
    op.create_table('uploads',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('extension', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('hash', name=op.f('pk_uploads'))
    )
    op.create_table('recipients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('zipcode', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('receive_letters', sa.Boolean(), nullable=True),
    sa.Column('country_code', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], name=op.f('fk_recipients_country_code_countries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipients'))
    )
    op.create_table('letters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('zipcode', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('event', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('signature', sa.String(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=True),
    sa.Column('allow_reuse', sa.Boolean(), nullable=False),
    sa.Column('specific_recipient_id', sa.Integer(), nullable=True),
    sa.Column('language_code', sa.String(), nullable=False),
    sa.Column('greeting_id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], name=op.f('fk_letters_country_code_countries')),
    sa.ForeignKeyConstraint(['greeting_id'], ['greetings.id'], name=op.f('fk_letters_greeting_id_greetings')),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], name=op.f('fk_letters_language_code_languages')),
    sa.ForeignKeyConstraint(['specific_recipient_id'], ['recipients.id'], name=op.f('fk_letters_specific_recipient_id_recipients')),
    sa.ForeignKeyConstraint(['upload_id'], ['users.id'], name=op.f('fk_letters_upload_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_letters'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('letters')
    op.drop_table('recipients')
    op.drop_table('uploads')
    op.drop_table('languages')
    op.drop_table('greetings')
    op.drop_table('countries')
    # ### end Alembic commands ###
