"""removal of the greeting field

Revision ID: fe734d68b2fd
Revises: b045b95f427f
Create Date: 2022-01-24 15:10:23.865529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe734d68b2fd'
down_revision = 'b045b95f427f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_letters_greeting_key_greetings', 'letters', type_='foreignkey')
    op.drop_column('letters', 'greeting_key')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('letters', sa.Column('greeting_key', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_letters_greeting_key_greetings', 'letters', 'greetings', ['greeting_key'], ['key'])
    # ### end Alembic commands ###
