name: docker-1lettre1sourire

on:
  push:
    branches:
      - "*"
    paths-ignore:
      - "**/README.md"
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  build:
    name: Tests ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: ubuntu-18.04 }
          - { os: ubuntu-20.04 }
          - { os: ubuntu-22.04 }
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
          fetch-depth: 0

      - name: Change scripts permissions
        run: chmod +x ./scripts/start_compose.sh && chmod +x ./scripts/stop_compose.sh

      - name: "Up docker containers"
        run: ./scripts/start_compose.sh -d

      - name: "Wait init docker containers"
        run: sleep 60

      - name: "Check app port"
        uses: nick-fields/retry@v2
        with:
          timeout_seconds: 15
          max_attempts: 3
          retry_on: error
          command: nc -zv 127.0.0.1 5000

      - name: "Check server"
        if: always()
        run: docker-compose -f docker-compose.yml top

      - name: "Check logs server"
        if: always()
        run: docker-compose -f docker-compose.yml logs

      - name: "Down docker containers"
        run: ./scripts/stop_compose.sh

  lint:
    name: lint
    runs-on: ubuntu-latest
    # needs: [build]
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
          fetch-depth: 0
      - name: Python Linter
        uses: sunnysid3up/python-linter@master
        with:
          source: "app"
          mypy-options: "--ignore-missing-imports --show-error-codes"
          pylint-options: "--rcfile=setup.cfg"
          isort-options: "-w 100"
          django: false
